### ISSUE TITLE
Option to disable extra logging

### ISSUE THREAD

**Issue by nox-404** [filipows/rxjs-retry-delay#1]
Hello,
Could you add an option to disable logging on line
`https://github.com/filipows/rxjs-retry-delay/blob/master/src/retry-delay.operator.ts#L49`
and `https://github.com/filipows/rxjs-retry-delay/blob/master/src/retry-delay.operator.ts#L53`

Like a verbose flag to enable them ?

(I could do a PR if needed)

**Comment by filipows** [comment]
Hi @nox-404, I like your idea. I'll be happy to get a PR if you want to do it.

**Comment by nox-404** [comment]
Well I found another way to implement such behavior with the latest rxjs, so I didn't look more into it...
